### ISSUE TITLE
test OneSentence1 z test_text_analysis.cpp nie przechodzi

### ISSUE THREAD

**Issue by brejman** [blstream/StudyBox_CV#21]
jak w tytule. Jeżeli to jest oczekiwany wynik, należy go zmienić/usunąć.

**Comment by dwegrowski** [comment]
Założenia tego testu powinny być takie, że olewa ten znak zapytania na początku i wykrywa zdanie następujące po nim.

**Comment by brejman** [comment]
Nie powinno być w takim razie
```
BOOST_CHECK(a.getStart() == 1 /* zamiast 0 */);
BOOST_CHECK(a.getEnd() == 9);
BOOST_CHECK(a.getType() == answer);
```
?
W każdym razie błąd jest w `BOOST_CHECK(a.getEnd() == 9);`, zwracane jest 10

**Comment by dwegrowski** [comment]
Powinno być tak jak mówisz. Chyba, że powinienem zmodyfikować kod i nie pomijać tego znaku na początku tylko zaznaczać go jako niesklasyfikowany o początku i końcu = 0.

**Comment by gajdzik** [comment]
Według mnie jest dobrze, chyba że były wprowadzane jakieś zmiany w algorytmie w zwracaniu wartości na którym miejscu znajduje się koniec zdania. Ten algorytm pomija "?", więc liczy to jako początek zdania ("?" znajduje się na zerowym miejscu, a "." na dziewiątym). Mi zwraca błąd właśnie jakby miało być BOOST_CHECK(a.getEnd() == 10);

**Comment by Sokolowski-Michal-Piotr** [comment]
Poprawione. Przyczyna: znaki diakrytyczne są reprezentowane za pomocą dwóch bajtów stąd marker końcowy występował na pozycji o jeden bajt dalej niż zakładał test. Problem z markerem początkowym wynikał z błędnego warunku pętli (nie uwzględniał szczególnego przypadku).
