### ISSUE TITLE
Kolizja nazw ::Rectangle przy kompilacji z MSVC

### ISSUE THREAD

**Issue by brejman** [blstream/StudyBox_CV#26]
klasa ::Rectangle wykorzystywana do segmentacji obrazu koliduje z funkcją o tej samej nazwie zadeklarowaną w wingdi.h. Powoduje to w najlepszym wypadku błędy linkera. Należałoby tą klasę wsadzić do jakiegoś namespace albo zmienić nazwę na taką, która nie koliduje.

**Comment by Sokolowski-Michal-Piotr** [comment]
Zdefiniowanie NOGDI rozwiązuje ten problem.
