### ISSUE TITLE
Błąd przy kompilacji pliku text_analysis.cpp

### ISSUE THREAD

**Issue by RafalAndrusieczko** [blstream/StudyBox_CV#27]
OS: Ubuntu 14.04
g++: 4.9

text_analysis.cpp
../../source/textanalysis/text_analysis.cpp: In function ‘std::vector<Markers> findQA(std::string)’:
../../source/textanalysis/text_analysis.cpp:97:71: error: no matching function for call to ‘transform(std::basic_string<char>::iterator, std::basic_string<char>::iterator, std::basic_string<char>::iterator, <unresolved overloaded function type>)’
     std::transform(text.begin(), text.end(),text.begin(), std::tolower);
                                                                       ^
../../source/textanalysis/text_analysis.cpp:97:71: note: candidates are:
In file included from /usr/include/c++/4.9/algorithm:62:0,
                 from ../../source/textanalysis/text_analysis.cpp:4:
/usr/include/c++/4.9/bits/stl_algo.h:4153:5: note: template<class _IIter, class _OIter, class _UnaryOperation> _OIter std::transform(_IIter, _IIter, _OIter, _UnaryOperation)
     transform(_InputIterator __first, _InputIterator __last,
     ^
/usr/include/c++/4.9/bits/stl_algo.h:4153:5: note:   template argument deduction/substitution failed:
../../source/textanalysis/text_analysis.cpp:97:71: note:   couldn't deduce template parameter ‘_UnaryOperation’
     std::transform(text.begin(), text.end(),text.begin(), std::tolower);
                                                                       ^
In file included from /usr/include/c++/4.9/algorithm:62:0,
                 from ../../source/textanalysis/text_analysis.cpp:4:
/usr/include/c++/4.9/bits/stl_algo.h:4190:5: note: template<class _IIter1, class _IIter2, class _OIter, class _BinaryOperation> _OIter std::transform(_IIter1, _IIter1, _IIter2, _OIter, _BinaryOperation)
     transform(_InputIterator1 __first1, _InputIterator1 __last1,
     ^
/usr/include/c++/4.9/bits/stl_algo.h:4190:5: note:   template argument deduction/substitution failed:
../../source/textanalysis/text_analysis.cpp:97:71: note:   candidate expects 5 arguments, 4 provided
     std::transform(text.begin(), text.end(),text.begin(), std::tolower);
                                                                       ^
make: *** [obj/x32/Debug/text_analysis.o] Error1

**Comment by dwegrowski** [comment]
Fix'd
