### ISSUE TITLE
Segmentacja rzuca wyjątek przy ustawieniu obrazu w skali szarości

### ISSUE THREAD

**Issue by Sokolowski-Michal-Piotr** [blstream/StudyBox_CV#42]
Segmentacja rzuca wyjątek przy ustawieniu obrazu w skali szarości

**Comment by sebastian-wieczorek-blstream** [comment]
Róbmy bugi na jira i przypisujmy do aktualnego sprintu, wtedy wszystko jest w jednym miejscu
